Repository systopia/de.systopia.xcm, pull requests merged in 2023-09, with the labels that each got.

#104 Add managed entities for "automation" and "configure_xcm" navigation menu items
  info.xml
  managed/Navigation__configure_xcm.mgd.php
  xcm.php
Labels: enhancement, status:reviewed and tested

#84 Add label for birth_date and gender_id fields
  CRM/Xcm/Tools.php
Labels: enhancement, status:needs review

#106 CiviCRM 5.60 compatibility
  CRM/Xcm/Configuration.php
  CRM/Xcm/CustomData.php
  CRM/Xcm/MatchingEngine.php
  CRM/Xcm/MatchingRule.php
  CRM/Xcm/Upgrader/Base.php
Labels: bug, status:reviewed and tested
